### ISSUE TITLE
Will the tool fix the continuous read operations on the AS3104T?

### ISSUE THREAD

**Issue by janrinze** [rgsilva/asustor-tools#1]
As you mentioned the daemon reads it's configuration constantly from disk.
Does that explain why the AS3104T is constantly generation disk access noises?

**Comment by rgsilva** [comment]
I'm not really sure, but it could be. For the original daemon you might need to contact Asustor on this matter. This tool, however, won't fix that, as the daemon will continue running. The fan speed tool will just be faster than it in changing the fan speed.
